export const baseDataRequestRating = {
  reviewer_name: "",
  reviewer_full_name: "",
  reviewer_email: "",
  reviewer_phone: "",
  reviewer_address: "",
  manager_name: "",
  manager_user_name: "",
  manager_location: "",
  job_location: "",
  manager_url: "",
  function_name: "",
  function_manager: "",
  used_function_from_manager: false,
  function_execution_date: "",
  problem_solver_manager_name: "",
  problem_to_be_solved: "",
  manager_helped_identify_problem: false,
  function_solved_problem: false,
  problem_existed_before_function: false,
  problem_existed_after_function: false,
  function_provided_solved_problem: false,
  provided_feedback_after_function: false,
  manager_applied_feedback: false,
  rating: 0,
  project_id: "",
};
